package signalUtils;

public enum SignalType {
    GAUSSIAN_NOISE,
    IMPULSE_NOISE,
    NOISE,
    RECTANGULAR,
    RECTANGULAR_SYMMETRICAL,
    SIN_FULL_WAVE,
    SIN_HALF_WAVE,
    SIN,
    TRIANGULAR,
    UNIT_IMPULSE,
    UNIT_STEP,
    FIXED_SIGNAL
}
